website/blueprints/anime.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, request, Blueprint

from website import app, db, login_required, get_right_side_bar
from website.models.models import Anime, Torrent
from website.forms.forms import AddAnimeForm, EditAnimeForm


anime_bp = Blueprint('anime', __name__, url_prefix='/anime', template_folder='../templates/anime')


@anime_bp.route('/')
def anime():
    return redirect(url_for('index.index'))


@anime_bp.route('/<int:anime_id>/')
@get_right_side_bar
def show_anime(anime_id):
    anime = Anime.query.get(anime_id)
    torrents = anime.get_alike_torrents()
    return render_template('anime.html', anime=anime, torrents=torrents)


@anime_bp.route('/add/', methods=['POST', 'GET'])
@login_required
def add_anime():
    form = AddAnimeForm(request.form)
    if request.method == 'GET':
        return render_template('add.html', form=form)
    if request.method == 'POST' and form.validate():
        print form.cn_name.dat
        db.session.add(form.set_anime())
        try:
            db.session.commit()
        except Exception as e:
            app.logger.error(e)
            flash('Add anime failed!')
        else:
            flash('Successfully added an anime!')
        return redirect(url_for('show_anime'))


@anime_bp.route('/edit/<int:anime_id>/', methods=['POST', 'GET'])
@login_required
def edit_anime(anime_id):
    form = EditAnimeForm(anime_id, formdata=request.form)
    if request.method == 'GET':
        if form.get_anime() is None:
            return 'ERROR 404: PAGE NOT FOUND!', 404
        else:
            form.set_form_value()
            return render_template('edit.html', form=form)
    if request.method == 'POST' and form.validate():
        form.update_anime()
        try:
            db.session.commit()
        except Exception as e:
            flash('Edit anime failed!')
        else:
            flash('Edit successfully finished!')
        return redirect(url_for('show_anime', anime_id=anime_id))


@anime_bp.route('/search/')
@get_right_side_bar
def search():
    if request.args.get('q'):
        info = request.args['q']
        try:
            anime_id = int(info)
            return redirect(url_for('.show_anime', anime_id=anime_id))
        except ValueError:
            animes = Anime.get_alike_animes(info)
            return render_template('search.html', animes=animes)
    else:
        flash('You need to type something to search!')
        return redirect(url_for('index.index'))

website/blueprints/bangumi.py
# -*- coding: utf8 -*-
import datetime

from flask import render_template, Blueprint

from website import app
from website.models.models import Anime, Torrent


bangumi_bp = Blueprint('bangumi', __name__, url_prefix='/animes', template_folder='../templates/bangumi')


@bangumi_bp.route('/')
@bangumi_bp.route('/today/')
def show_animes_today():
    now = datetime.date.today()
    this_year = now.year
    this_season = now.month/3 + 1
    weekday = now.weekday()
    animes = Anime.query.filter_by(year=this_year, season=this_season, weekday=weekday)
    torrents = {anime.cn_name: anime.get_alike_torrents(app.config['TORRENTS_PER_ANIME']) for anime in animes}
    return render_template('today.html', animes=animes, torrents=torrents)


@bangumi_bp.route('/season/')
def show_animes_this_season():
    [monday, tuesday, wednesday, thursday, friday, saturday, sunday] = \
        [Anime.query.filter_by(year=2014, season=2, weekday=i)
         for i in range(7)]
    return render_template('season.html', monday=monday, tuesday=tuesday, wednesday=wednesday,
                           thursday=thursday, friday=friday, saturday=saturday, sunday=sunday)


@bangumi_bp.route('/all/')
@bangumi_bp.route('/all/<int:page>/')
def show_all_animes(page=1):
    animes = Anime.query.paginate(page, app.config['ANIMES_PER_PAGE'], False).items
    return render_template('all.html', animes=animes)

website/templates/bangumi/all.html
{% extends "./base.html" %}
{% block body %}
        所有 bangumi：<br/>
  {% for anime in animes %}
        <a href="{{ url_for('anime.show_anime', anime_id=anime.id) }}">{{ anime.cn_name }}</a>
        <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
  {% endfor %}

  {% if animes.has_prev %}
    <a href="{{ url_for('anime.show_all_animes', page=anime.prev_num) }}"><< 上一页</a>
  {% endif %}

  {% if animes.has_next %}
    <a href="{{ url_for('anime.show_all_animes', page=anime.next_num) }}">下一页 >></a>
  {% endif %}

{% endblock %}

website/templates/bangumi/season.html
{% extends "./base.html" %}
{% block body %}
        本季新番表：<br/>
        <div>
          星期一：<br/>
          {% for anime in monday %}
            {{ anime.cn_name }} <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
          {% endfor %}
        </div>
        <div>
          星期二：<br/>
          {% for anime in tuesday %}
            {{ anime.cn_name }} <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
          {% endfor %}
        </div>
        <div>
          星期三：<br/>
          {% for anime in wednesday %}
            {{ anime.cn_name }} <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
          {% endfor %}
        </div>
        <div>
          星期四：<br/>
          {% for anime in thursday %}
            {{ anime.cn_name }} <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
          {% endfor %}
        </div>
        <div>
          星期五：<br/>
          {% for anime in friday %}
            {{ anime.cn_name }} <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
          {% endfor %}
        </div>
        <div>
          星期六：<br/>
          {% for anime in saturday %}
            {{ anime.cn_name }} <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
          {% endfor %}
        </div>
        <div>
          星期日：<br/>
          {% for anime in sunday %}
            {{ anime.cn_name }} <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
          {% endfor %}
        </div>
{% endblock %}

website/templates/bangumi/today.html
{% extends "./base.html" %}
{% block body %}
        本日更新：<br/>
  {% for anime in animes %}
        {{ anime.cn_name }} <a href="{{ url_for('anime.edit_anime', anime_id=anime.id) }}">EDIT</a><br/>
        {% for torrent in torrents[anime.cn_name] %}
          <a href="{{ torrent.link }}">{{ torrent.title }}</a><br/>
        {% endfor %}
  {% endfor %}
{% endblock %}