website/blueprints/anime.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, request, Blueprint

from website import app, db, login_required, get_right_side_bar
from website.models.models import Anime, Torrent
from website.forms.forms import AddAnimeForm, EditAnimeForm


anime_bp = Blueprint('anime', __name__, url_prefix='/anime', template_folder='../templates/anime')


@anime_bp.route('/')
def anime():
    return redirect(url_for('index.index'))


@anime_bp.route('/<int:anime_id>/')
@get_right_side_bar
def show_anime(anime_id):
    anime = Anime.query.get(anime_id)
    torrents = anime.get_alike_torrents()
    return render_template('anime.html', anime=anime, torrents=torrents)


@anime_bp.route('/add/', methods=['POST', 'GET'])
@login_required
def add_anime():
    form = AddAnimeForm(request.form)
    if request.method == 'GET':
        return render_template('add.html', form=form)
    if request.method == 'POST' and form.validate():
        print form.cn_name.dat
        db.session.add(form.set_anime())
        try:
            db.session.commit()
        except Exception as e:
            app.logger.error(e)
            flash('Add anime failed!')
        else:
            flash('Successfully added an anime!')
        return redirect(url_for('show_anime'))


@anime_bp.route('/edit/<int:anime_id>/', methods=['POST', 'GET'])
@login_required
def edit_anime(anime_id):
    form = EditAnimeForm(anime_id, formdata=request.form)
    if request.method == 'GET':
        if form.get_anime() is None:
            return 'ERROR 404: PAGE NOT FOUND!', 404
        else:
            form.set_form_value()
            return render_template('edit.html', form=form)
    if request.method == 'POST' and form.validate():
        form.update_anime()
        try:
            db.session.commit()
        except Exception as e:
            flash('Edit anime failed!')
        else:
            flash('Edit successfully finished!')
        return redirect(url_for('show_anime', anime_id=anime_id))


@anime_bp.route('/search/')
@get_right_side_bar
def search():
    if request.args.get('q'):
        info = request.args['q']
        try:
            anime_id = int(info)
            return redirect(url_for('.show_anime', anime_id=anime_id))
        except ValueError:
            animes = Anime.get_alike_animes(info)
            return render_template('search.html', animes=animes)
    else:
        flash('You need to type something to search!')
        return redirect(url_for('index.index'))

website/blueprints/bangumi.py
# -*- coding: utf8 -*-
import datetime

from flask import render_template, Blueprint

from website import app
from website.models.models import Anime, Torrent


bangumi_bp = Blueprint('bangumi', __name__, url_prefix='/animes', template_folder='../templates/bangumi')


@bangumi_bp.route('/')
@bangumi_bp.route('/today/')
def show_animes_today():
    now = datetime.date.today()
    this_year = now.year
    this_season = now.month/3 + 1
    weekday = now.weekday()
    animes = Anime.query.filter_by(year=this_year, season=this_season, weekday=weekday)
    torrents = {anime.cn_name: anime.get_alike_torrents(app.config['TORRENTS_PER_ANIME']) for anime in animes}
    return render_template('today.html', animes=animes, torrents=torrents)


@bangumi_bp.route('/season/')
def show_animes_this_season():
    [monday, tuesday, wednesday, thursday, friday, saturday, sunday] = \
        [Anime.query.filter_by(year=2014, season=2, weekday=i)
         for i in range(7)]
    return render_template('season.html', monday=monday, tuesday=tuesday, wednesday=wednesday,
                           thursday=thursday, friday=friday, saturday=saturday, sunday=sunday)


@bangumi_bp.route('/all/')
@bangumi_bp.route('/all/<int:page>/')
def show_all_animes(page=1):
    animes = Anime.query.paginate(page, app.config['ANIMES_PER_PAGE'], False).items
    return render_template('all.html', animes=animes)

website/blueprints/index.py
from functools import wraps

from flask import session, flash, url_for, g, redirect, render_template, request, Blueprint

from website.models.models import User
from website import oid, get_right_side_bar


index_bp = Blueprint('index', __name__, template_folder='../templates/index')


@oid.after_login
def create_or_login(resp):
    user = User.query.filter_by(google_account=resp.email).first()
    if user is None:
        user = User(nickname=resp.nickname or resp.fullname, google_account=resp.email,
                    openid=resp.identity_url)
        if user.register():
            flash(u"You've successfully registered and signed in!")
        else:
            flash(u'Register failed!')
            return redirect(oid.get_next_url())
    else:
        flash("You've successfully logged in!")
    session['user_id'] = user.id
    g.user = user
    return redirect(oid.get_next_url())


@index_bp.route('/login', methods=['GET', 'POST'])
@oid.loginhandler
@get_right_side_bar
def login():
    if session.get('user_id'):
        flash("You've logged in!")
        return redirect(oid.get_next_url())
    if request.method == 'POST':
        openid = request.form.get('openid')
        if openid:
            return oid.try_login(openid, ask_for=['email', 'nickname', 'fullname'])
    return render_template('login.html', next=oid.get_next_url(),
                           error=oid.fetch_error())


@index_bp.route('/logout')
@get_right_side_bar
def logout():
    session.pop('user_id', None)
    session.pop('nickname')
    flash(u'You were signed out')
    return redirect(oid.get_next_url())


@index_bp.route('/')
@get_right_side_bar
def index():
    return render_template('hello.html')

website/templates/base.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content=""/>
  <title>{{ title }}</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}"/>
  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  
  <!--[if lt IE 9]>
    <script src="../../assets/js/html5shiv.js"></script>
    <script src="../../assets/js/respond.min.js"></script>
    <!--如果浏览器版本小于IE10则显示广告js-->
    <script src=""></script>

  <![endif]-->
    {% block header %}{% endblock %}
</head>
<body>
<header role="banner" class="navbar navbar-fixed-top">
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('index.index') }}">Brand</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('bangumi.show_animes_today') }}">本日更新</a></li>
          <li><a href="{{ url_for('bangumi.show_animes_this_season') }}">本季新番</a></li>
          <li><a href="{{ url_for('bangumi.show_all_animes') }}">所有动画</a></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">常用链接<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{{ url_for('userview.index_view') }}">管理用户</a></li>
              <li><a href="{{ url_for('animeview.index_view') }}">管理动画</a></li>
              <li><a href="{{ url_for('torrentview.index_view') }}">管理种子</a></li>
              <li><a href="{{ url_for('animereviewview.index_view') }}">管理漫评</a></li>
              <li><a href="{{ url_for('actorquoteview.index_view') }}">管理台词</a></li>
              <li class="divider"></li>
              <li><a href="{{ url_for('anime.show_anime', anime_id=1) }}">测试动画</a></li>
              <li><a href="{{ url_for('anime.search') }}?q=1">测试搜索</a></li>
              <li><a href="{{ url_for('anime.search') }}?q=sdfwer">测试搜索</a></li>
              <li><a href="{{ url_for('anime.search') }}?q=虫师">测试搜索</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search"
                   method=get action="{{ url_for('anime.search') }}">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search" name="q">
          </div>
          <button type="submit" class="btn btn-default">搜索</button>
        </form>
        <ul class="nav navbar-nav navbar-right" style="margin-right:0">
          {% if g.user: %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"  style="padding-top:0; padding-bottom:0">
              <img class="avatar img-circle" src="" />
              {{ g.user.nickname }}
            </a>
            <ul class="dropdown-menu">
              <li><a href="{{ url_for('anime.add_anime') }}">我要推荐</a></li>
              <li class="divider"></li>
              <li><a href="{{ url_for('index.logout') }}">登出</a></li>
            </ul>
          </li>
          {% else: %}
          <li class="dropdown">
            <a href="{{ url_for('index.login') }}">登录</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>
</header>
<div class="container" id="main-container" style="">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  {{ message|safe }}
</div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  <div class="col-md-9">
    <!----------------------ADD TEMPLATE CONTENT HERE!------------------------>
    {% block body %}{% endblock %}
  </div>
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">推荐榜</div>
      <ul class="list-group">
        {% for anime in g.newest_added_animes %}
        <li class="list-group-item"><a href="{{ url_for('anime.show_anime', anime_id=anime.id) }}">{{ anime.cn_name }}</a> </li>
        {% endfor %}
        <li class="list-group-item">EVA</li>
        <li class="list-group-item">Ghost in the Shell</li>
        <li class="list-group-item">Stand Alone Complex</li>
        <li class="list-group-item">十二国记</li>
      </ul>

      <div class="panel-heading">最近更新</div>
      <ul class="list-group">
        {% for anime in g.newest_updated_animes %}
        <li class="list-group-item"><a href="{{ url_for('anime.show_anime', anime_id=anime.id) }}">{{ anime.cn_name }}</a> </li>
        {% endfor %}
        <li class="list-group-item">物语系列二</li>
        <li class="list-group-item">狼与香辛料</li>
        <li class="list-group-item">Death Note</li>
        <li class="list-group-item">叛逆的鲁鲁修<div></div></li>
        <li class="list-group-item">花开物语</li>
      </ul>
    </div>
  </div>
</div>
<footer>
  <hr>
  <div class="container">
    <p class="pull-right"><a href="#">返回顶部</a></p>
    <ul class="footer-links">
      <li><a href="http://windrunner.info/hi-acg/">关于本站</a></li>
      <li class="muted">·</li>
      <li><a href="http://windrunner.info/hi-acg/">赞助本站</a></li>
      <li class="muted">·</li>
      <li><a href="http://windrunner.info/hi-acg/">提供建议</a></li>
      <li class="muted">·</li>
      <li><a href="mailto:kxxoling@gmail.com">联系站长</a></li>
      <li class="muted">·</li>
      <li><a href="">交换友链</a></li>
    </ul>
  </div>
</footer>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

{% block footer %}{% endblock %}
</body>
</html>